spring:
  datasource:
    username: root1
    password: Arun@40321
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
servlet:
multipart:
max-file-size: 10MB
max-request-size: 10MB

#project.poster: posters

project:
 poster: MoviePoster
base:
   url: "http://localhost:8080"

